---
- name: create a file on rvweb01
  hosts: raiani_apache
  become: yes 
  gather_facts: no
  tasks:
    - name: touch a file
      ansible.builtin.file:
        path: /root/ansible_touchfile.tmp
        state: touch
    - name: rsync file to docker host
      ansible.posix.synchronize:
        archive: yes
        src: /root/ansible_touchfile.tmp
        dest: rsync://docker.lan.raiani.com/home/docker/tmp/
      delegate_to: rvweb01.lan.raiani.com
