---
- name: fix python install on Debian 11
  hosts: all
  become: yes 
  gather_facts: no
  tasks:
    - name: install python-is-python3
      ansible.builtin.file:
        path: /root/ansible_touchfile.tmp
        state: touch
    - name: rsync file to docker host
      ansible.posix.synchronize:
        archive: yes
        set_remote_user: no
        src: /root/ansible_touchfile.tmp
        dest: docker.lan.raiani.com:/home/docker/tmp/
      delegate_to: rvweb01.lan.raiani.com
