---
- name: reload nginx proxy
  hosts: raiani_docker
  remote_user: docker
  tasks:
  - name: actually restart
    community.docker.docker_container_exec:
      container: nginx-proxy
      command: nginx -s reload
    register: result
