---
- name: fix python install on Debian 11
  hosts: all
  become: yes 
  gather_facts: no
  tasks:
    - name: update apt-cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
    - name: install python-is-python3
      apt:
        name: python-is-python3
        state: present


