---
- hosts: raiani_syncthing
  become: true

  tasks:
  - name: Add the Syncthing apt repository
    apt_repository:
      repo: 'deb https://apt.syncthing.net/ syncthing stable'
      state: present
      filename: 'syncthing'

  - name: Add the Syncthing GPG key
    apt_key:
      url: https://syncthing.net/release-key.txt
      state: present

  - name: Install Syncthing
    apt:
      name: syncthing
      state: latest
      update_cache: yes

  - name: Create the Syncthing systemd service unit
    template:
      src: ../templates/syncthing.service.j2
      dest: /etc/systemd/system/syncthing.service
      mode: 0644

  - name: Enable the Syncthing systemd service
    systemd:
      name: syncthing
      state: started
      enabled: yes

  - name: Create the syncthing user
    user:
      name: syncthing
      shell: /bin/false
      state: present


