---
- name: reload nginx proxy
  hosts: raiani_docker
  become: yes
  gather_facts: no

  tasks:
    - name: install docker py
      ansible.builtin.pip:
        name: docker
    - name: actually restart
      docker_container:
        name: nginx-proxy
        state: started
        command: nginx -s reload

