---
- name: reload nginx proxy
  hosts: raiani_docker
  become: yes
  gather_facts: no

  tasks:
    - name: install docker py
      ansible.builtin.pip:
        name: docker
    - name: actually restart
      community.docker.docker_container_exec:
        container: nginx-proxy
        command: nginx -s reload

